/*
 * Copyright 2016 Ignacio del Valle Alles idelvall@brutusin.org.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.brutusin.rpc.actions.websocket;

import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import org.brutusin.rpc.Descriptible;
import org.brutusin.rpc.websocket.Topic;
import org.brutusin.rpc.websocket.WebsocketAction;

/**
 * Topic testing service. No included by default. User in embedded test mode.
 *
 * @author Ignacio del Valle Alles idelvall@brutusin.org
 */
public class PublishAction extends WebsocketAction<PublishActionInput, Void> implements Descriptible {

    private final Topic topic;

    public PublishAction(Topic topic) {
        this.topic = topic;
    }

    @Override
    public Void execute(PublishActionInput input) throws Exception {
        topic.fire(input.getFilter(), input.getMessage());
        return null;
    }

    @Override
    public Type getInputType() {
        return new ParameterizedType() {
            public Type[] getActualTypeArguments() {
                return new Type[]{topic.geFilterType(), topic.getMessageType()};
            }

            public Type getRawType() {
                return PublishActionInput.class;
            }

            public Type getOwnerType() {
                return null;
            }
        };
    }

    @Override
    public String getDescription() {
        return "Autogenerated publisher service for topic `" + topic.getId() + "`. This service is only available when testing topics, and not in the complete application";
    }
}
